export const SITE_CONFIG = {
  name: "Artist Nation",
  tagline: "We Don't Organize Events. We Create Experiences.",
  description:
    "Bangalore's premier event management company for corporate events, product launches, movie promotions, brand activations, celebrity management, IT company outings, and luxury experiences across India.",
  url: "https://artistnation.in",
  locale: "en_IN",
  phone: "+91 98765 43210",
  email: "hello@artistnation.in",
  whatsapp: "+919876543210",
  address: {
    street: "MG Road, Brigade Road",
    city: "Bangalore",
    state: "Karnataka",
    postalCode: "560001",
    country: "IN",
  },
  social: {
    instagram: "https://instagram.com/artistnation",
    linkedin: "https://linkedin.com/company/artistnation",
    youtube: "https://youtube.com/@artistnation",
  },
  stats: {
    events: 1000,
    brands: 200,
    years: 15,
    artists: 500,
  },
} as const;

export const SEO_KEYWORDS = [
  "Artist Nation Bangalore",
  "Artist Nation event management",
  "Artist Nation India",
  "Artist Nation corporate events",
  "Artist Nation movie promotions",
  "Artist Nation product launches",
  "event management",
  "events",
  "event conductors",
  "event organizers",
  "Bangalore event management",
  "corporate event management",
  "product launch events",
  "movie promotion events",
  "brand activation",
  "celebrity management",
  "luxury events",
  "conference management",
  "team outings",
  "IT company outings",
  "corporate team outings Bangalore",
  "event management company India",
  "best event management company",
  "premium event organizers",
  "Fortune 500 event management",
] as const;
