export const SITE_CONFIG = {
  name: "Artist Nation",
  tagline: "We Don't Organize Events. We Create Experiences.",
  description:
    "Founded more than a decade ago by Mr. Cigi George and Mr. Shaji Thomas Philip with 35+ years of combined experience. Artist Nation is a full-service event, brand management, and entertainment agency operating across Bangalore, Chennai, and Cochin.",
  url: "https://artistnation.in",
  locale: "en_IN",
  phone: "+91 9080100200",
  secondaryPhone: "+91 9539696969",
  contactPersons: [
    { name: "Main Desk", phone: "+91 9080100200" },
    { name: "Mr. Shaji Thomas Philip", phone: "+91 9539696969" },
  ],
  founders: [
    { name: "Mr. Cigi George", role: "Co-Founder & Event Guru" },
    { name: "Mr. Shaji Thomas Philip", role: "Co-Founder & Brand Guru" },
  ],
  email: "hello@artistnation.in",
  whatsapp: "+919080100200",
  address: {
    street: "MG Road, Brigade Road",
    city: "Bangalore",
    state: "Karnataka",
    postalCode: "560001",
    country: "IN",
  },
  offices: [
    {
      city: "Bangalore (HQ)",
      address: "MG Road, Brigade Road, Bangalore, Karnataka 560001",
      phone: "+91 9080100200",
      email: "bangalore@artistnation.in",
      mapUrl: "https://maps.google.com/?q=Artist+Nation+Bangalore",
      isHQ: true,
    },
    {
      city: "Chennai",
      address: "Anna Salai, Nungambakkam, Chennai, Tamil Nadu 600034",
      phone: "+91 9080100200",
      email: "chennai@artistnation.in",
      mapUrl: "https://maps.google.com/?q=Artist+Nation+Chennai",
      isHQ: false,
    },
    {
      city: "Cochin (Kochi)",
      address: "MG Road, Marine Drive, Kochi, Kerala 682011",
      phone: "+91 9539696969",
      email: "cochin@artistnation.in",
      mapUrl: "https://maps.google.com/?q=Artist+Nation+Cochin",
      isHQ: false,
    },
  ],
  social: {
    instagram: "https://instagram.com/artistnation",
    linkedin: "https://linkedin.com/company/artistnation",
    youtube: "https://youtube.com/@artistnation",
  },
  stats: {
    events: 1000,
    brands: 200,
    years: 35,
    artists: 500,
  },
} as const;

export const SEO_KEYWORDS = [
  "Artist Nation Bangalore",
  "Artist Nation event management",
  "Artist Nation India",
  "Artist Nation corporate events",
  "Artist Nation movie promotions",
  "Artist Nation product launches",
  "event management",
  "events",
  "event conductors",
  "event organizers",
  "Bangalore event management",
  "corporate event management",
  "product launch events",
  "movie promotion events",
  "brand activation",
  "celebrity management",
  "luxury events",
  "conference management",
  "team outings",
  "IT company outings",
  "corporate team outings Bangalore",
  "event management company India",
  "best event management company",
  "premium event organizers",
  "Fortune 500 event management",
] as const;
