export const SITE_CONFIG = {
  name: "Artist Nation Entertainments",
  tagline: "We Don't Organize Events. We Create Experiences.",
  description:
    "Founded more than a decade ago by Mr. Cigi George and Mr.S.T.Philip with a decade of excellence. Artist Nation Entertainments is a full-service event, brand management, and entertainment agency with operations across India with offices at Bengaluru, Chennai and Kochi.",
  url: "https://artistnation.in",
  locale: "en_IN",
  phone: "+91 94446 96130",
  secondaryPhone: "+91 94446 96130",
  contactPersons: [
    { name: "Main Desk", phone: "+91 94446 96130" },
  ],
  founders: [
    { name: "Mr. Cigi George", role: "Event Alchemist" },
    { name: "Mr. S.T.Philip", role: "Event Alchemist" },
  ],
  email: "George@artistnation.in",
  secondaryEmail: "Philip@artistnation.in",
  emails: ["George@artistnation.in", "Philip@artistnation.in"],
  whatsapp: "+919444696130",
  address: {
    street: "MG Road, Brigade Road",
    city: "Bangalore",
    state: "Karnataka",
    postalCode: "560001",
    country: "IN",
  },
  offices: [
    {
      city: "Bangalore (HQ)",
      address: "",
      phone: "+91 94446 96130",
      email: "George@artistnation.in",
      secondaryEmail: "Philip@artistnation.in",
      mapUrl: "https://maps.google.com/?q=Artist+Nation+Entertainments+Bangalore",
      isHQ: true,
    },
    {
      city: "Chennai",
      address: "Anna Salai, Nungambakkam, Chennai, Tamil Nadu 600034",
      phone: "+91 94446 96130",
      email: "George@artistnation.in",
      secondaryEmail: "Philip@artistnation.in",
      mapUrl: "https://maps.google.com/?q=Artist+Nation+Entertainments+Chennai",
      isHQ: false,
    },
    {
      city: "Cochin (Kochi)",
      address: "MG Road, Marine Drive, Kochi 682011",
      phone: "+91 94446 96130",
      email: "George@artistnation.in",
      secondaryEmail: "Philip@artistnation.in",
      mapUrl: "https://maps.google.com/?q=Artist+Nation+Entertainments+Cochin",
      isHQ: false,
    },
  ],
  social: {
    instagram: "https://instagram.com/artistnation",
    linkedin: "https://linkedin.com/company/artistnation",
    youtube: "https://youtube.com/@artistnation",
  },
  stats: {
    events: 1000,
    brands: 200,
    years: 15,
    artists: 500,
  },
} as const;

export const SEO_KEYWORDS = [
  "Artist Nation Entertainments",
  "Artist Nation Entertainments Bangalore",
  "Artist Nation Entertainments event management",
  "Artist Nation Entertainments India",
  "Artist Nation Entertainments corporate events",
  "Artist Nation Entertainments movie promotions",
  "Artist Nation Entertainments product launches",
  "Artist Nation",
  "Artist Nation Bangalore",
  "Artist Nation event management",
  "Artist Nation India",
  "event management",
  "events",
  "event conductors",
  "event organizers",
  "Bangalore event management",
  "corporate event management",
  "product launch events",
  "movie promotion events",
  "brand activation",
  "celebrity management",
  "luxury events",
  "conference management",
  "team outings",
  "IT company outings",
  "corporate team outings Bangalore",
  "event management company India",
  "best event management company",
  "premium event organizers",
  "Fortune 500 event management",
] as const;
